# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: Pete Correia
description: Consultant Creative Technologist & Front-end Developer based in London, UK.
available: November 2015

author:
  name: Pete Correia
  email: pete@petecorreia.com
  github: petecorreia
  twitter: petecorreia

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "case-studies"
    values:
      section: "case-study"
      class: "case-study"

responsive_images:
  - name: regular
    sizes:
    - size: 320
      retina: true
    - size: 480
      retina: true
    - size: 768
      retina: true
    - size: 1024
      retina: true
  - name: full-width
    sizes:
    - size: 320
      retina: true
    - size: 480
      retina: true
    - size: 768
      retina: true
    - size: 1024
      retina: true
    - size: 1280
      retina: true
    - size: 1440
      retina: true
    - size: 1920
      retina: false

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: pretty

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

highlighter: null

gems:
  - jekyll-sitemap